
export const FETCH_SERVICES = 'FETCH_SERVICES';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT_DETAIL = 'FETCH_PRODUCT_DETAIL';
export const ADD_WISHLIST = 'ADD_WISHLIST';
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST';
export const GET_WISHLIST = 'GET_WISHLIST';
export const SUBMIT_WISHLIST = 'SUBMIT_WISHLIST';
export const SUBMIT_CONTACTFORM = 'SUBMIT_CONTACTFORM';
